# T002 Robot — 8 joints
joints:
  - name: waist_joint
    motor_id: 4
    interface: can0
    interface_type: can
    motor_type: DM
    motor_model: 0
    master_id_offset: 1
    direction: 1.0
    zero_offset: 0.0
    estop_kd: 0.0
    mit_kd: 0.0

  - name: neck_yaw_joint
    motor_id: 3
    interface: can0
    interface_type: can
    motor_type: DM
    motor_model: 2
    master_id_offset: 1
    direction: 1.0
    zero_offset: 0.0
    estop_kd: 0.1
    mit_kd: 0.08

  - name: neck_pitch_joint
    motor_id: 1
    interface: can0
    interface_type: can
    motor_type: STW
    motor_model: 0
    master_id_offset: 0
    direction: 1.0
    zero_offset: 0.0
    estop_kd: 0.1
    mit_kd: 0.04

  - name: neck_roll_joint
    motor_id: 2
    interface: can0
    interface_type: can
    motor_type: STW
    motor_model: 0
    master_id_offset: 0
    direction: 1.0
    zero_offset: 0.0
    estop_kd: 0.1
    mit_kd: 0.04

  - name: wheel_left_yaw_joint
    motor_id: 5
    interface: can0
    interface_type: can
    motor_type: DM
    motor_model: 0
    master_id_offset: 1
    direction: 1.0
    zero_offset: 0.0
    estop_kd: 0.0
    mit_kd: 0.0

  - name: wheel_left_roll_joint
    motor_id: 6
    interface: can0
    interface_type: can
    motor_type: DM
    motor_model: 0
    master_id_offset: 1
    direction: 1.0
    zero_offset: 0.0
    estop_kd: 0.0
    mit_kd: 0.0

  - name: wheel_right_yaw_joint
    motor_id: 7
    interface: can0
    interface_type: can
    motor_type: DM
    motor_model: 0
    master_id_offset: 1
    direction: 1.0
    zero_offset: 0.0
    estop_kd: 0.0
    mit_kd: 0.0

  - name: wheel_right_roll_joint
    motor_id: 8
    interface: can0
    interface_type: can
    motor_type: DM
    motor_model: 0
    master_id_offset: 1
    direction: 1.0
    zero_offset: 0.0
    estop_kd: 0.0
    mit_kd: 0.0