# T002 Controller (8 joints)
/**:
  controller_manager:
    ros__parameters:
      update_rate: 250
      t002_controller:
        type: t002_controller/T002Controller
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

  joint_state_broadcaster:
    ros__parameters:
      update_rate: 250
      joints:
        - waist_joint
        - neck_yaw_joint
        - neck_pitch_joint
        - neck_roll_joint
        - wheel_left_yaw_joint
        - wheel_left_roll_joint
        - wheel_right_yaw_joint
        - wheel_right_roll_joint

  t002_controller:
    ros__parameters:
      update_rate: 250
      command_topic: "~/command"
      joints: [waist_joint, neck_yaw_joint, neck_pitch_joint, neck_roll_joint,
               wheel_left_yaw_joint, wheel_left_roll_joint, wheel_right_yaw_joint, wheel_right_roll_joint]
      command_interfaces: [effort]
      state_interfaces: [position, velocity]
      joint_modes: [position, position, torque, torque, position, velocity, position, velocity]
      joint_limits:
        - -1.57; 1.57; -3.14; 3.14; -0.35; 0.35; -0.35; 0.35
        - -6.28; 6.28; -50.0; 50.0; -6.28; 6.28; -50.0; 50.0
      pd:
        - 1.0; 0.6; 1.5; 0.15; 0.0; 0.0; 0.0; 0.0
        - 5.0; 0.1; 2.5; 0.0; 5.0; 0.1; 2.5; 0.0
      effort_limits:
        - -5.0; 5.0; -5.0; 5.0; -1.5; 1.5; -1.5; 1.5
        - -5.0; 5.0; -5.0; 5.0; -5.0; 5.0; -5.0; 5.0
      default_joint_positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
